# Generated by Django 5.2.5 on 2025-08-17 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100, unique=True)),
                ('adresse_mail', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('etat', models.CharField(choices=[('connecte', 'Connecté'), ('deconnecte', 'Déconnecté')], default='deconnecte', max_length=20)),
                ('situation', models.CharField(choices=[('bloque', 'Bloqué'), ('normal', 'Normal'), ('termine', 'Terminé')], default='normal', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='converse.utilisateur')),
            ],
            bases=('converse.utilisateur',),
        ),
        migrations.CreateModel(
            name='UtilisateurClassique',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='converse.utilisateur')),
            ],
            bases=('converse.utilisateur',),
        ),
        migrations.CreateModel(
            name='DemandeDeConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_denvoie', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to='converse.utilisateur')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_recues', to='converse.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='EspaceDeConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(to='converse.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.ManyToManyField(to='converse.utilisateur')),
                ('espace_de_conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='converse.espacedeconversation')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoie', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='converse.espacedeconversation')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to='converse.utilisateur')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='converse.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de résolution'), ('resolu', 'Résolu')], default='en_attente', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problemes_signales', to='converse.utilisateur')),
            ],
        ),
    ]
