# Generated by Django 5.2.5 on 2025-08-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0002_message_lu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='participants',
        ),
    ]
