# Generated by Django 5.2.5 on 2025-08-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0003_remove_contact_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bloque_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_bloques', to='converse.utilisateur'),
        ),
    ]
