# Generated by Django 5.2.5 on 2025-08-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converse', '0004_contact_bloque_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutDeFrappe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_en_train_decrire', models.BooleanField(default=False)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibles_de_frappe', to='converse.utilisateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuts_de_frappe', to='converse.utilisateur')),
            ],
            options={
                'unique_together': {('utilisateur', 'cible')},
            },
        ),
    ]
